
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wuiqdtzodqshamhndued.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1aXFkdHpvZHFzaGFtaG5kdWVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyNzkxMDMsImV4cCI6MjA1Nzg1NTEwM30.K0TKpZj4rShQesMsHh-WKe3CA5Rj9T5uKpRU12ANo6A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
